### ISSUE TITLE
Generation strips relative path, causing issues

### ISSUE THREAD

**Issue by 5HT2** [videogame-hacker/som.codes#1]
Hi, I rendered the site like so:
```
som.codes ❯ cargo run --release
Finished release [optimized] target(s) in 0.45s
Running `target/release/som_codes`
[i] Copying assets…
[i] Rendering main page…
[+] dist/index.html
[i] Rendering blog archive…
[+] dist/blog/index.html
[i] Rendering blog posts…
[+] dist/blog/2019-12-07/deploying-static-sites/index.html
[+] dist/blog/2020-02-01/qmk-reactive-rgb/index.html
[+] dist/blog/2019-07-12/transcoding-music/index.html
[+] dist/blog/2020-01-07/hide-signal-phone-numbers/index.html
[+] dist/blog/2019-12-30/jvm-hackery-noverify/index.html
[i] Rendering error pages…
[+] dist/404.html
```

And opened `dist/index.html` in my browser.

Surprisingly, assets are broken: [https://p.l1v.in/⋅˙⋅‥.⋮∵.png](https://p.l1v.in/⋅˙⋅‥.⋮∵.png)

I came up with a workaround:
```bash
cd dist
for FILE in $(rg --files-with-matches "/assets"); do sed -i 's/\/assets/.\/assets/g' "$FILE"; done
```

Which basically just replaces `/assets` with `./assets` in all files that have it.

After the fix [https://p.l1v.in/˙⋆⋯⋅⋯⋯∵.png](https://p.l1v.in/˙⋆⋯⋅⋯⋯∵.png)

Though I assume this also means links to `./blog` are also broken, in either way it would be nice to use relative paths by default :)

**Comment by 5HT2** [comment]
(I assume this isn't an issue at all when using nginx which you likely are)

**Comment by char** [comment]
Yeah, this site assumes that it lives at the webroot, which can't happen with `file://` URIs.

If you want to view it locally, I suggest running `python3 -m http.server` or similar from the `dist` directory. `siru` will support starting a local web-server soon, too (as well as watching the `src` directory for changes).
